fyp/fyp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

fyp/website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('player/', views.player, name='player'),
    path('add_injury/', views.add_injury, name='add_injury'),
    path('view_player/edit/<int:injury_id>/', views.edit_injury, name='edit_injury'),
    path('view_player/', views.player_view, name='view_player'),
    path('view_player/get_player_injuries/', views.get_player_injuries, name='get_player_injuries'),
    path('view_player/get_player_details/', views.get_player_details, name='get_player_details'),
    path('view_player/delete_player/', views.delete_player, name='delete_player'),
    path('view_player/edit/<int:id>/delete_injury/', views.delete_injury, name='delete_injury'),
    path('injury_prediction/', views.predict_injury, name='injury_prediction'),
    path('injury_scan_acl/', views.detect_acl, name='injury_scan_acl')
]

fyp/website/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.conf import settings
from django.contrib.auth import get_user_model


class CustomUser(AbstractUser):
    is_business_user= models.BooleanField(blank=True, null=True)


class Player(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete= models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    position = models.CharField(max_length = 10)
    date_of_birth = models.DateField()
    height = models.IntegerField()
    weight = models.IntegerField()
    country = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Injury(models.Model):
    player = models.ForeignKey(Player, on_delete= models.CASCADE)
    injury = models.CharField(max_length=50)
    injury_start_date = models.DateField()
    injury_end_date = models.DateField(null=True, blank=True)
    injury_age = models.IntegerField(blank=True)
    injured = models.BooleanField(default = False)

fyp/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import HttpResponse, FileResponse
from django.urls import reverse
from django.core.files.uploadedfile import TemporaryUploadedFile

from datetime import date
import os
import tempfile
import base64
from .predictions import clean_and_predict
from .generatePDF import generate_pdf
from .forms import SignUpForm, PlayerForm, InjuryForm
from .models import Player, Injury
from roboflow import Roboflow


def home(request): 
    return render(request, 'home.html', {})

def login_user(request): 
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            messages.success(request, "Successfully logged in.")
            return redirect('home')
        else:
            messages.success(request, "Invalid user.")
            return redirect('login')
    else:
        return render(request, 'login.html', {})

def logout_user(request): 
    logout(request)
    messages.success(request, "Successfully logged out.")
    return redirect('home')

def register_user(request): 
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request,user)
            messages.success(request, "Successfully registered.")
            return redirect('home')
    else:
        form = SignUpForm()
        return render(request, 'register.html', {'form':form})
    if form.errors:
        errors_list = []
        for field in form:
            if field.errors: 
                errors_list.append(field.errors)
        form.errors.clear()
    return render(request, 'register.html', {'form':form, 'errors_list':errors_list})

def player(request):
    if request.user.is_authenticated:
        form = PlayerForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                add_player = form.save(commit=False)
                add_player.user = request.user
                add_player.save()
                messages.success(request, "Player successfully created.")
                return redirect('home')
        errors_list = []
        if form.errors:
            for field in form:
                if field.errors: 
                    errors_list.append(field.errors)
        form.errors.clear()
        return render(request, 'player.html', {'form':form, 'errors_list':errors_list})
    else: 
        messages.error(request, "You have to log in to access this page.")
        return redirect('home')

def add_injury(request):
    title = 'Add Injury'
    if request.user.is_authenticated:
        try:
            form = InjuryForm(user=request.user)
            if request.method == 'POST':
                form = InjuryForm(request.POST, user=request.user)
                
                if form.is_valid():
                    form.save()
                    messages.success(request, "Injury successfully added.")
                    return redirect('home')
                
                errors_list = []
                if form.errors:
                    for field in form:
                        if field.errors: 
                            errors_list.append(field.errors)
                form.errors.clear()
                return render(request, 'injury.html', {'form':form, 'errors_list':errors_list, 'title': title})
        except ValidationError as e:
            messages.error(request, e.messages[0])
            return redirect('player')
    else: 
        messages.error(request, "You have to log in to access this page.")
        return redirect('home')

    return render(request, 'injury.html', {'form': form, 'title': title})

def player_view(request):
    if request.user.is_authenticated:
        players = Player.objects.filter(user=request.user)
        if players.count() == 0: 
            messages.error(request,'A player has to be created before you can access this page.')
            return redirect('player')
        return render(request, 'view_player.html', {'players': players})
    else: 
        messages.error(request, "Not logged in.")
        return redirect('home')

def get_player_injuries(request):
    selected_player = request.GET.get('selected_player', None)
    
    injuries = Injury.objects.filter(player=selected_player).order_by('-injury_start_date')
    if bool(injuries) == False:
        return HttpResponse("This player has no injuries.")
    
    injuries_html = (
        f'<thead>'
        f'<tr>'
        f'<th scope="col">Injury</th>'
        f'<th scope="col">Date Injured</th>'
        f'<th scope="col">Date Recovered</th>'
        f'<th scope="col">Age of Injury</th>'
        f'<th scope="col">Action</th>'
        f'</tr>'
        f'</thead>'
    )
    
    for injury in injuries:
        end_date = injury.injury_end_date
        if end_date is None:
            end_date = date.today()
            row_class = 'table-danger' 
        else: 
            row_class = ""

        edit_url = reverse('edit_injury', args=[injury.id])
        injuries_html += (
            f'<tr class="{row_class}">'
            f'<td>{injury.injury}</td>'
            f'<td>{injury.injury_start_date}</td>'
            f'<td>{end_date}</td>'
            f'<td>{injury.injury_age}</td>'
            f'<td><a href="{edit_url}" class="btn btn-outline-secondary btn-sm">Edit Injury</a></td>'
            f'</tr>'
        )

    return HttpResponse(injuries_html)

def edit_injury(request,injury_id):
    try:
        injury = Injury.objects.get(id=injury_id) 
        title = 'Edit Injury'
        if request.method == 'POST':
            form = InjuryForm(request.POST, instance=injury, user=request.user)
            if form.is_valid():
                form.save()
                messages.success(request,'Injury successfully edited.')
                return redirect('view_player')
            errors_list = []
            if form.errors:
                for field in form:
                    if field.errors: 
                        errors_list.append(field.errors)
            form.errors.clear()
            return render(request, 'injury.html', {'form':form, 'errors_list':errors_list, 'title': title, 'injury_id': injury_id})
        else:
            form = InjuryForm(instance=injury, user=request.user)
    except: 
        messages.error(request, "This player is not linked to your account. ")
        return redirect('view_player')

    return render(request, 'injury.html', {'form': form, 'title': title, 'injury_id': injury_id})

def get_player_details(request):
    selected_player = request.GET.get('selected_player', None)
    player_details = Player.objects.filter(id=selected_player).first()
    details_html = ''
    details_html += (
        f'<tr>'
        f'<th>Full Name:</th>'
        f'<td>{player_details.first_name} {player_details.last_name}</td>'
        f'</tr>'
        f'<tr>'
        f'<th>Position:</th>'
        f'<td>{player_details.position}</td>'
        f'</tr>'
        f'<tr>'
        f'<th>Date of Birth:</th>'
        f'<td>{player_details.date_of_birth}</td>'
        f'</tr>'
        f'<tr>'
        f'<th>Height(cm):</th>'
        f'<td>{player_details.height}</td>'
        f'</tr>'
        f'<tr>'
        f'<th>Weight(kg):</th>'
        f'<td>{player_details.weight}</td>'
        f'</tr>'
        f'<tr>'
        f'<th>Country:</th>'
        f'<td>{player_details.country}</td>'
        f'</tr>'
        f'</br>'
    )
    return HttpResponse(details_html)

def delete_player(request):
    player_id = request.POST.get('player_id')
    player_count = Player.objects.filter(user=request.user).count()
    delete_player = Player.objects.filter(id=player_id).first()
    delete_player.delete()
    if player_count == 1:
        redirect_url = reverse('home')
    else:
        redirect_url = reverse('view_player')
    messages.success(request, "Player successfully deleted.")
    return HttpResponse(redirect_url)

def delete_injury(request,id):
    delete_injury = Injury.objects.filter(id=id).first()
    delete_injury.delete()
    redirect_url = reverse('view_player')
    messages.success(request, "Injury successfully deleted.")
    return HttpResponse(redirect_url)

def predict_injury(request):
    very_low_risk_paragraphs = ["None specifically, but avoid overtraining and ensure proper form.", "Focus on maintaining flexibility, strength, and endurance. Include exercises like squats, lunges, hamstring curls, calf raises, and plyometrics for lower body strength. Incorporate agility drills and balance exercises to improve proprioception.", "Continue regular strength and conditioning programs. Ensure proper warm-up and cool-down routines. Focus on technique during all exercises."]
    low_risk_paragraphs = ["High-impact exercises without proper progression or supervision.", "Emphasize core strength, leg strength, and balance. Exercises may include planks, side planks, bridging, and stability ball exercises for core stability. Include exercises like squats, lunges, hamstring curls, calf raises, and plyometrics for lower body strength. ", "Monitor training load to avoid sudden increases in intensity or volume. Pay attention to recovery and include active recovery sessions."]

fyp/website/templates/add_injury.html
{% extends 'base.html' %}

{% block content %}
<meta name="csrf-token" content="{{ csrf_token }}">
<div class = "col-md-6 offset-md-3">
<br/>
<h1>{{ title }}</h1>
<br/>
<form method="POST">
    {% csrf_token %}
    {% if errors_list %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for error in errors_list %}  
			  		{{ error }}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		
	{% endif %}

{% if title == 'Edit Injury'%}

    <div style="display: none;">
        {{ form.player }}
    </div>
{% elif form.one_player %}
        <div class="col-auto my-1">
            {{ form.player }}
        </div>
        <br/>
    
{% else %}

    <div style="display: none;">
        {{ form.player }}
    </div>

{% endif %}

    <div class="col-auto my-1">
        {{ form.injury }} 
    </div>
    <br/>
    <div class="form-floating">
        {{ form.injury_start_date }}
        <label for="floatingInput">Injury Start Date</label>
    </div>
    <br/>
    <div class="form-floating" id="id_injury_end_date">
        {{ form.injury_end_date }}
        <label for="floatingInput">Injury End Date</label>
        <br/>
    </div>
    <div>
        <input type="checkbox" id="id_injured" name="injured" {% if form.injured.value %}checked{% endif %}>
        <label for="id_injured">Injured</label>
    </div>
    <br/>
    <button type="submit" class="btn btn-outline-primary">{{ title }}</button>
    {% if title == "Edit Injury" %}
    <button id="delete_injury" type="button" class="btn btn-outline-danger delete-injury" data-injury-id = "{{ injury_id }}">Delete Injury</button>
    {% endif %}

</form>
</div>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Injury</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this injury? This can <strong>not</strong> be undone.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
        </div>
      </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var injuredCheckbox = document.getElementById('id_injured');
        var deleteInjury = document.getElementById('delete_injury');
        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        console.log(injuredCheckbox)

        if (deleteInjury){
            deleteInjury.addEventListener('click', function(){
                var injuryId = deleteInjury.getAttribute('data-injury-id');
                document.getElementById('confirmDelete').setAttribute('data-injury-id', injuryId);
            
                var deleteModal = new bootstrap.Modal(document.getElementById('deleteConfirmationModal'));
                deleteModal.show();
            })
        }

        document.getElementById('confirmDelete').addEventListener('click', function() {
            var injuryId = this.getAttribute('data-injury-id');
            
            console.log('Confirmed deletion for injuryId ID:', injuryId);
            
            var xhr = new XMLHttpRequest();
            xhr.open('POST', 'delete_injury/', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', csrfToken); 
            
            xhr.onload = function() {
                if (xhr.status === 200) {

                    console.log('Player deleted successfully');
                    window.location.href = xhr.responseText;
                } else {
                    console.log('Error deleting player');
                }
            };

            xhr.send('injury_id=' + encodeURIComponent(injuryId));
            
            var deleteModal = bootstrap.Modal.getInstance(document.getElementById('deleteConfirmationModal'));
            deleteModal.hide();
            
        });
    
        toggleInjuryEndDateVisibility();


        injuredCheckbox.addEventListener('change', function () {
            toggleInjuryEndDateVisibility();
        });


        function toggleInjuryEndDateVisibility() {
            var injuryEndDateField = document.getElementById('id_injury_end_date');

            if (injuredCheckbox.checked) {
                injuryEndDateField.style.display = 'none';
            } else {
                injuryEndDateField.style.display = 'block'; 
            }
        }
        
    });
  </script>

{% endblock %}

fyp/website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="icon" href="{% static 'FP-logo-removebg.png' %}" type="image">
    <title>Final Year Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% include 'navbar.html' %}
    <div class = "container">
    <br/>
        {% if messages %}
          {% for message in messages %}
            <div class="toast-container position-fixed bottom-0 end-0 p-3">
              <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="background-color: whitesmoke !important;">
                <div class="toast-header">
                  {% load static %}
                  <img src="{% static 'FP-logo.jpg' %}" width="40" class="rounded me-2" alt="...">
                  <strong class="me-auto">Football Physician</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                  {{message}}
                </div>
              </div>
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>
    <footer class="footer mt-auto py-3 bg-dark">
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        var toastElList = [].slice.call(document.querySelectorAll('.toast'));
        var toastList = toastElList.map(function(toastEl) {
          return new bootstrap.Toast(toastEl).show();
        });
      });
    </script>
  </body>
</html>

fyp/website/templates/home.html
{% extends 'base.html' %}

{% block content %}

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-2">Welcome to Football Physician</h1>
        <h4>A platform for helping predict, detect and prevent injuries</h4>
        <br/>
      </div>
    </div>
    <hr>
    <br/>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Get Started Today</h2>
          <p>Welcome to Football Physician, the gateway to enhanced ACL injury management and prevention. Harnessing data analytics, we offer insights into player well-being and game readiness. Register to enroll players, and monitor their health through our user-friendly dashboard. Gain an edge with tailored reports and practical advice to maintain your players at their best.</p>
          {% if user.is_authenticated %} 
          <p><a class="btn btn-secondary" href="{% url 'player'%}" role="button">Try now »</a></p>
          {% else %}
          <p><a class="btn btn-secondary" href="{% url 'register'%}" role="button">Register »</a></p>
          {% endif %}
        </div>
        <div class="col-md-4">
          <h2>Prediction</h2>
          <p>Our predictive analytics tool assesses the risk of an ACL injury for each player. By analysing historical data and current metrics, we can forecast a players risk of ACL injury. This allows coaches and medical staff to make informed decisions about training loads, recovery times, and game-day readiness. Mitigate risks and optimise your players' performance by utilising our prediction system.</p>
          {% if user.is_authenticated %} 
          <p><a class="btn btn-secondary" href="{% url 'injury_prediction'%}" role="button">Try now »</a></p>
          {% else %}
          <p><a class="btn btn-secondary" href="{% url 'register'%}" role="button">Register »</a></p>
          {% endif %}
        </div>
        <div class="col-md-4">
          <h2>Detection</h2>
          <p>Designed for immediate and accurate diagnosis without the wait for hospital consultations. Our system allows for identification of ACL issues promptly, bypassing delays often encountered with external medical evaluations of MRI scans. With this direct access to critical insights, you can initiate tailored recovery plans right away, ensuring swift and informed responses to ACL injuries.</p>
          {% if user.is_authenticated %} 
          <p><a class="btn btn-secondary" href="{% url 'injury_scan_acl'%}" role="button">Try now »</a></p>
          {% else %}
          <p><a class="btn btn-secondary" href="{% url 'register'%}" role="button">Register »</a></p>
          {% endif %}
        </div>
      </div>

    </div> <!-- /container -->

  </main>

{% endblock %}

fyp/website/templates/injury.html
{% extends 'base.html' %}

{% block content %}
<meta name="csrf-token" content="{{ csrf_token }}">
<div class = "col-md-6 offset-md-3">
<br/>
<h1>{{ title }}</h1>
<br/>
<form method="POST">
    {% csrf_token %}
    {% if errors_list %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for error in errors_list %}  
			  		{{ error }}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		
	{% endif %}

{% if title == 'Edit Injury'%}

    <div style="display: none;">
        {{ form.player }}
    </div>
{% elif form.one_player %}
        <div class="col-auto my-1">
            {{ form.player }}
        </div>
        <br/>
    
{% else %}

    <div style="display: none;">
        {{ form.player }}
    </div>

{% endif %}

    <div class="col-auto my-1">
        {{ form.injury }} 
    </div>
    <br/>
    <div class="form-floating">
        {{ form.injury_start_date }}
        <label for="floatingInput">Injury Start Date</label>
    </div>
    <br/>
    <div class="form-floating" id="id_injury_end_date">
        {{ form.injury_end_date }}
        <label for="floatingInput">Injury End Date</label>
        <br/>
    </div>
    <div>
        <input type="checkbox" id="id_injured" name="injured" {% if form.injured.value %}checked{% endif %}>
        <label for="id_injured">Injured</label>
    </div>
    <br/>
    <button type="submit" class="btn btn-outline-primary">{{ title }}</button>
    {% if title == "Edit Injury" %}
    <button id="delete_injury" type="button" class="btn btn-outline-danger 
    delete-injury" data-injury-id = "{{ injury_id }}">Delete Injury</button>
    {% endif %}

</form>
</div>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Injury</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this injury? This can <strong>not</strong> be undone.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
        </div>
      </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var injuredCheckbox = document.getElementById('id_injured');
        var deleteInjury = document.getElementById('delete_injury');
        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        console.log(injuredCheckbox)

        if (deleteInjury){
            deleteInjury.addEventListener('click', function(){
                var injuryId = deleteInjury.getAttribute('data-injury-id');
                document.getElementById('confirmDelete').setAttribute('data-injury-id', injuryId);
            
                var deleteModal = new bootstrap.Modal(document.getElementById('deleteConfirmationModal'));
                deleteModal.show();
            })
        }

        document.getElementById('confirmDelete').addEventListener('click', function() {
            var injuryId = this.getAttribute('data-injury-id');
            
            console.log('Confirmed deletion for injuryId ID:', injuryId);
            
            var xhr = new XMLHttpRequest();
            xhr.open('POST', 'delete_injury/', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', csrfToken); 
            
            xhr.onload = function() {
                if (xhr.status === 200) {

                    console.log('Player deleted successfully');
                    window.location.href = xhr.responseText;
                } else {
                    console.log('Error deleting player');
                }
            };

            xhr.send('injury_id=' + encodeURIComponent(injuryId));
            
            var deleteModal = bootstrap.Modal.getInstance(document.getElementById('deleteConfirmationModal'));
            deleteModal.hide();
            
        });
    
        toggleInjuryEndDateVisibility();


        injuredCheckbox.addEventListener('change', function () {
            toggleInjuryEndDateVisibility();
        });


        function toggleInjuryEndDateVisibility() {
            var injuryEndDateField = document.getElementById('id_injury_end_date');

            if (injuredCheckbox.checked) {
                injuryEndDateField.style.display = 'none';
            } else {
                injuryEndDateField.style.display = 'block'; 
            }
        }
        
    });
  </script>

{% endblock %}

fyp/website/templates/injury_scan_acl.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-3">
        <h1>ACL injury scan</h1>
        <br/>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input style="display:none" class="form-control" id="imageInput" type="file" name="image" accept="image/*" required>
            <button type="button" id="customButton" class="btn btn-secondary">Choose File</button>
            {% if img_name %}
            <span id="fileName">{{img_name}}</span>
            {% else %}
            <span id="fileName">No file chosen</span>
            {% endif %}
            <br/>
            <br/>
            <div id="imagePreview">
                {% if image %}
                <img src="{{ image }}" alt="Prepopulated Image" style="max-width: 100%; max-height: 200px;">
                {% endif %}
            </div>
            <br/>
            <br/>
            <button type="submit" class="btn btn-outline-primary">Upload Image</button>
        </form>
    </div>

    {% if injury %}
    <div class="col-md-9">
    <br/>
    <br/>
        <div class="accordion" id="classification">
            <div class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <strong>Prediction</strong>
                </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#classification">
                    <div class="accordion-body">
                        You have a <strong>{{injury}}</strong>.
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <strong>Recovery Time</strong>
                </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#classification">
                    <div class="accordion-body">
                        {{ paragraphs.0 }}
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    <strong>Rehabilitation Advice</strong>
                </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#classification">
                    <div class="accordion-body">
                        {{ paragraphs.1 }}
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    <strong>Prevention and Strengthening</strong>
                </button>
                </h2>
                <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#classification">
                    <div class="accordion-body">
                        {{ paragraphs.2 }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
    {% endif %}
</div>

<script>
    function handleFileInputChange(event) {
        const file = event.target.files[0];
        const reader = new FileReader();
        
        reader.readAsDataURL(file);
        reader.onload = function(event) {
            const imageUrl = event.target.result;
            document.getElementById('imagePreview').innerHTML = '<img src="' + imageUrl + '" alt="Selected Image" style="max-width: 100%; max-height: 200px;">';
            document.getElementById('fileName').textContent = file.name;
        };
    }

    document.getElementById('imageInput').addEventListener('change', handleFileInputChange);

    document.getElementById('customButton').addEventListener('click', function() {
        document.getElementById('imageInput').click(); 
    });
</script>

{% endblock %}